<a href="https://colab.research.google.com/github/LizaMilovanova/Final-work/blob/main/%D0%97%D0%B0%D0%B2%D0%B4%D0%B0%D0%BD%D0%BD%D1%8F_3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import altair as alt
from vega_datasets import data
import plotly.express as px

In [17]:
df = data.wheat()

In [19]:
df.head()

   year  wheat  wages
0  1565   41.0   5.00
1  1570   45.0   5.05
2  1575   42.0   5.08
3  1580   49.0   5.12
4  1585   41.5   5.15

In [20]:
df.shape

(52, 3)

In [21]:
df.duplicated().sum()

np.int64(0)

In [22]:
df.isna().sum()

year     0
wheat    0
wages    2
dtype: int64

In [23]:
alt.renderers.enable('default')

df = data.wheat()

bars = alt.Chart(df).mark_bar().encode(
    x='wheat:Q',
    y='year:O'
)

text = alt.Chart(df).mark_text(
    align='left',
    dx=3
).encode(
    x='wheat:Q',
    y='year:O',
    text='wheat:Q'
)

bars + text

alt.LayerChart(...)

In [24]:
iowa_data = data.iowa_electricity()

chart2 = alt.Chart(iowa_data).mark_area(opacity=0.7).encode(
    x='year:T',
    y='net_generation:Q',
    color='source:N'
).properties(title='Виробництво електроенергії в Айові за джерелами')

chart2.display()

alt.Chart(...)

In [25]:
df_iris = px.data.iris()

fig = px.scatter(
    df_iris,
    x='sepal_width',
    y='sepal_length',
    color='species',
    size='petal_length',
    hover_data=['petal_width'],
    title='Аналіз датасету Ірисів'
)

fig.show()